[package]
name = "the_admiral_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
regex  = "1.10.6"
rand   = "0.8.5"

serenity = "0.12.2"
tokio    = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
